import React from "react";
import { Course } from "../types";

interface CourseListProps {
  courses: Course[];
  onViewCourse: (index: number) => void;
  onAIGeneratedCourse?: (course: Course) => void; // Optional prop for AI courses
}

// Example button to simulate AI API course generation
const exampleAICourse: Course = {
  title: "AI Generated Course",
  description: "This course was generated by AI.",
  lessons: [
    { title: "Introduction", content: "Welcome to your AI course!" },
    { title: "Lesson 1", content: "AI-generated content goes here." },
  ],
};

const CourseList: React.FC<CourseListProps> = ({
  courses,
  onViewCourse,
  onAIGeneratedCourse,
}) => (
  <div className="mt-8">
    <h2 className="text-xl font-bold mb-2">Saved Courses</h2>
    {onAIGeneratedCourse && (
      <button
        className="mb-4 px-3 py-1 bg-green-600 text-white rounded"
        onClick={() => onAIGeneratedCourse(exampleAICourse)}
      >
        Generate AI Course
      </button>
    )}
    {courses.length === 0 ? (
      <p className="text-gray-600">No courses saved yet.</p>
    ) : (
      <ul className="space-y-2">
        {courses.map((course, idx) => (
          <li
            key={course.title + idx}
            className="bg-white border rounded p-3 flex justify-between items-center"
          >
            <span className="font-medium">{course.title}</span>
            <button
              className="px-3 py-1 bg-blue-600 text-white rounded"
              onClick={() => onViewCourse(idx)}
            >
              View
            </button>
          </li>
        ))}
      </ul>
    )}
  </div>
);

export default CourseList;
